# theme = "onedark"
theme = "base16_transparent"

[editor]
true-color = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false # show hidden files

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.lsp]
display-messages = true

# mappings
[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]

# as `X` in vim
[keys.normal.g]
q = ":reflow"

[keys.normal.space]
q = ":quit"
w = ":write"
